from __future__ import annotations


TEXT = {
    "en": {
        "panel_summary": "This dataset appears to be panel data: an entity ID and a time variable are available. Use OLS as a baseline and Panel Fixed Effects as the main model.",
        "cross_section_summary": "This dataset appears to be cross-sectional. OLS is a suitable baseline for a continuous outcome.",
        "binary_summary": "A binary outcome is available. Logit and Probit are suitable options for binary dependent variables.",
        "unknown_summary": "The data structure is not clear yet. Review variable roles and explore the data before modeling.",
        "panel_rationale_observations": "The data contain repeated observations for the same entity over time.",
        "panel_rationale_fe": "Panel Fixed Effects can control for time-invariant unobserved differences across entities.",
        "panel_rationale_baseline": "OLS can be used as a baseline, but it should not be the only model for panel data.",
        "ols_rationale": "OLS is a simple baseline model for continuous outcomes.",
        "binary_rationale": "Logit and Probit are designed for binary outcomes.",
        "action_apply_recommended": "Apply recommended variable setup",
        "action_apply_main": "Apply recommended main model setup",
        "action_run_baseline": "Run OLS baseline model",
        "action_run_main": "Run recommended main model",
        "warn_dummy_explosion": "Some categorical variables have many categories. Dummy encoding may create too many variables.",
        "warn_review_roles": "Planner recommendations are rule-based. Review them before running a model.",
        "reason_numeric_y": "Numeric measure; possible continuous dependent variable.",
        "reason_binary_y": "Binary variable; possible binary dependent variable.",
        "reason_main_x": "Numeric measure with a name that often indicates a key explanatory variable.",
        "reason_control": "Numeric measure with a name commonly used as a control variable.",
        "reason_categorical_control": "Categorical variable with manageable cardinality; can be used only if dummy encoding is enabled.",
        "panel_model_reason": "Panel FE is recommended because repeated observations exist for the same entity over time.",
        "ols_model_reason": "OLS is suitable as a baseline for continuous outcomes.",
        "logit_model_reason": "Logit is suitable when the dependent variable is binary.",
        "probit_model_reason": "Probit is an alternative binary-outcome model.",
        "data_structure_panel": "panel data",
        "data_structure_cross_section": "cross-sectional data",
        "data_structure_binary": "binary outcome available",
        "data_structure_unknown": "unknown",
    },
    "zh": {
        "panel_summary": "检测到这份数据可能是面板数据：存在个体 ID 和时间变量。建议将 OLS 作为基准模型，并将面板固定效应作为主模型。",
        "cross_section_summary": "这份数据更接近截面数据。若因变量为连续数值变量，OLS 可作为合适的基准模型。",
        "binary_summary": "检测到可用的二元结果变量。Logit 和 Probit 适用于二元因变量。",
        "unknown_summary": "当前数据结构尚不清晰。建议先检查变量角色并进行数据探索。",
        "panel_rationale_observations": "数据中存在同一个体在多个时间期的重复观测。",
        "panel_rationale_fe": "面板固定效应可以控制个体层面不随时间变化的不可观测差异。",
        "panel_rationale_baseline": "OLS 可作为基准模型，但不应作为面板数据的唯一模型。",
        "ols_rationale": "OLS 适合作为连续型因变量的基准模型。",
        "binary_rationale": "Logit 和 Probit 适用于二元结果变量。",
        "action_apply_recommended": "应用推荐变量设置",
        "action_apply_main": "应用推荐主模型设置",
        "action_run_baseline": "先运行 OLS 基准模型",
        "action_run_main": "运行推荐主模型",
        "warn_dummy_explosion": "部分分类变量类别较多，虚拟变量编码可能生成过多变量。",
        "warn_review_roles": "分析建议基于规则生成。运行模型前请先检查并确认。",
        "reason_numeric_y": "数值变量，可作为连续型因变量候选。",
        "reason_binary_y": "二元变量，可作为二元因变量候选。",
        "reason_main_x": "数值变量，且变量名常用于表示核心解释变量。",
        "reason_control": "数值变量，变量名常见于控制变量设定。",
        "reason_categorical_control": "分类变量且类别数量可控；仅在启用虚拟变量编码后进入模型。",
        "panel_model_reason": "存在同一个体随时间重复观测，因此建议使用面板固定效应。",
        "ols_model_reason": "OLS 适合作为连续型因变量的基准模型。",
        "logit_model_reason": "Logit 适用于二元因变量。",
        "probit_model_reason": "Probit 可作为二元因变量的替代模型。",
        "data_structure_panel": "面板数据",
        "data_structure_cross_section": "截面数据",
        "data_structure_binary": "存在二元结果变量",
        "data_structure_unknown": "未知",
    },
}


def planner_text(language: str, key: str) -> str:
    lang = "zh" if language == "zh" else "en"
    return TEXT[lang].get(key, TEXT["en"].get(key, key))
